version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  reverse-proxy:
        build: ./nginx-reverse-proxy
        ports:
            - 80:80
  

networks:
    default:
        external:
            name: mynetwork
